markdown: redcarpet
highlighter: pygments

title: Cevelop
logo-small: /img/logo-white.png
logo: /img/logo.png

name: Cevelop C++ IDE
description: The C++ IDE for professional developers
url: http://cevelop.com
